services:
  postgresql:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  bot:
    build:
      context: ./bot
      dockerfile: ./bot.Dockerfile
    depends_on:
      - scrapper
    ports:
      - "8090:8090"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      SCRAPPER_BASE_URL: http://scrapper:8080
    networks:
      - backend

  scrapper:
    build:
      context: ./scrapper
      dockerfile: ./scrapper.Dockerfile
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgresql:5432/scrapper
      BOT_BASE_URL: http://bot:8090
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend: { }
