app:
  scheduler:
    enable: true
    interval: 30000
    force-check-delay: 30000

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

api:
  bot:
    baseUrl: ${BOT_BASE_URL:http://localhost:8090}
  github:
    baseUrl: ${GITHUB_BASE_URL:https://api.github.com}
  stackoverflow:
    baseUrl: ${STACKOVERFLOW_BASE_URL:https://api.stackexchange.com/2.3}

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
