app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

spring:
  application:
    name: scrapper

api:
  bot:
    baseUrl: ${BOT_BASE_URL:[http://localhost:8090]}
  github:
    baseUrl: ${GITHUB_BASE_URL:[https://api.github.com]}
  stackoverflow:
    baseUrl: ${STACKOVERFLOW_BASE_URL:[https://api.stackexchange.com/2.3]}

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
