app:
  scheduler:
    enable: true
    interval: 30000
    force-check-delay: 60000
  database-access-type: jpa
  useQueue: true

kafka:
  updateTopicName: "Updates"
  partitions: 1
  replicas: 1

spring:
  application:
    name: scrapper
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  liquibase:
    enabled: false
    drop-first: false
    change-log: migrations/master.xml
    default-schema: public
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    open-in-view: true

management:
  server:
    port: 8081
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "info, health, prometheus"
      path-mapping:
        prometheus: "metrics"

api:
  bot:
    baseUrl: ${BOT_BASE_URL:http://localhost:8090}
  github:
    baseUrl: ${GITHUB_BASE_URL:https://api.github.com}
  stackoverflow:
    baseUrl: ${STACKOVERFLOW_BASE_URL:https://api.stackexchange.com/2.3}

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

retry:
  # const, line, exp
  strategy: line
  maxAttempt: 4
  delay: 1000
  multiplier: 2
  retryableStatusCodes:
    - 400
    - 404
    - 500

bucket:
  capacity: 3
  refillAmount: 3
  refillTime: 10s
