bot:
  telegramToken: ${BOT_TOKEN:token}

kafka:
  updateTopicName: "Updates"
  partitions: 1
  replicas: 1

spring:
  application:
    name: bot
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: "bot"
  jackson:
    time-zone: UTC

api:
  scrapper:
    baseUrl: ${SCRAPPER_BASE_URL:http://localhost:8080}

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
