bot:
  telegramToken: ${BOT_TOKEN:token}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

management:
  server:
    port: 8091
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "info, health, prometheus"
      path-mapping:
        prometheus: "metrics"

api:
  scrapper:
    baseUrl: ${SCRAPPER_BASE_URL:http://localhost:8080}

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
